source/WTT/WTT.Web.ManagementPortal/Models/LoginDTO.cs
namespace WTT.Web.ManagementPortal.Models
{
    public class LoginDTO
    {
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

source/WTT/WTT.Web.ManagementPortal/Models/OdobriVrijemeDTO.cs
using System;

namespace WTT.Web.ManagementPortal.Models
{
    public class OdobriVrijemeDTO
    {
        public int DjelatnikId { get; set; }
        public DateTime Datum { get; set; }
    }
}

source/WTT/WTT.Web.ManagementPortal/Models/TimesDTO.cs
using System;
using System.Collections.Generic;
using WTT.Common.DTO;

namespace WTT.Web.ManagementPortal.Models
{
    public class TimesDTO
    {
        public string DjelatnikIme { get; set; }
        public int DjelatnikId { get; set; }
        public string DjelatnikTim { get; set; }

        public DateTime Datum { get; set; }

        public List<ProjectDTO> Evidencija { get; set; }

        public string Napomena { get; set; }
    }
}

source/WTT/WTT.Web.ManagementPortal/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using WTT.Web.ManagementPortal.Models;

namespace WTT.Web.ManagementPortal.Controllers
{
    [AllowAnonymous]
    public class AccountController : Controller
    {
        private readonly Services.IAuthorizationService _authorizationService;

        public AccountController(Services.IAuthorizationService authorizationService)
        {
            _authorizationService = authorizationService;
        }

        [HttpGet]
        public IActionResult Login()
        {
            if (this.User.Identity.IsAuthenticated)
            {
                return RedirectToPage("/TimeTrackingPage");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginDTO loginModel)
        {
            if (ModelState.IsValid)
            {
                var result = await _authorizationService.SignInUserAsync(loginModel.Username, loginModel.Password);

                if (result)
                {
                    if (Request.Query.Keys.Contains("ReturnUrl"))
                    {
                        return Redirect(Request.Query["ReturnUrl"][0]);
                    }
                    else
                    {
                        return RedirectToPage("/TimeTrackingPage");
                    }
                }
            }

            ModelState.AddModelError("", "Failed to login");

            return View();
        }



        public async Task<IActionResult> Logout()
        {
            await _authorizationService.SignOutUserAsync();

            return RedirectToPage("/TimeTrackingPage");
        }
    }
}

source/WTT/WTT.Web.ManagementPortal/Controllers/TimeManagementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using WTT.Common.Repositories;
using WTT.Common.Services;
using WTT.Web.ManagementPortal.Models;

namespace WTT.Web.ManagementPortal.Controllers
{
    [Authorize(Roles = "Direktor, Voditelj tima")]
    public class TimeManagementController : Controller
    {
        private readonly IDjelatnikRepository _djelatnikRepository;
        private readonly IProjectService _projectService;

        public TimeManagementController(IDjelatnikRepository djelatnikRepository, IProjectService projectService)
        {
            _djelatnikRepository = djelatnikRepository;
            _projectService = projectService;
        }

        [HttpGet]
        public async Task<IActionResult> OdobriVrijeme()
        {
            var djelatnikId = Convert.ToInt32(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var djelatnici = await _djelatnikRepository.GetDjelatnici(djelatnikId);

            var selectList = new List<SelectListItem>();
            foreach(var djelatnik in djelatnici)
            {
                selectList.Add(new SelectListItem(djelatnik.Name, djelatnik.DjelatnikId.ToString()));
            }

            ViewBag.SelectListDjelatnika = selectList;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> OdobriVrijeme(OdobriVrijemeDTO odobriVrijeme)
        {
            var djelatnik = await _djelatnikRepository.GetDjelatnik(odobriVrijeme.DjelatnikId);
            var (evidencija, napomena) = await _projectService.GetProjectTimes(odobriVrijeme.DjelatnikId, odobriVrijeme.Datum);
            var timesDTO = new TimesDTO
            {
                DjelatnikId = odobriVrijeme.DjelatnikId,
                DjelatnikIme = $"{djelatnik.Ime} {djelatnik.Prezime}",
                DjelatnikTim = djelatnik.Tim.Naziv,
                Evidencija = evidencija,
                Datum = odobriVrijeme.Datum,
                Napomena = napomena
            };

            return View("Odobravanje", timesDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Odobravanje(TimesDTO timesDTO)
        {
            await _projectService.SaveProjectTimes(timesDTO.Evidencija, timesDTO.DjelatnikId, timesDTO.Datum, timesDTO.Napomena);

            return RedirectToAction("OdobriVrijeme");
        }

        [HttpGet]
        public async Task<IActionResult> GetProjects()
        {
            var projects = await _projectService.GetProjectTimes(1, DateTime.Today);

            return new JsonResult(projects);
        }
    }
}

source/WTT/WTT.Web.ManagementPortal/Pages/TimeTrackingPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WTT.Common.DTO;
using WTT.Common.Services;
using WTT.Web.ManagementPortal.Models;

namespace WTT.Web.ManagementPortal.Pages
{
    [IgnoreAntiforgeryToken(Order = 1001)]
    public class TimeTrackingPageModel : PageModel
    {
        private readonly IProjectService _projectService;

        public TimesDTO Evidencija { get; private set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public DateTime RequestedDate { get; set; }

        public TimeTrackingPageModel(IProjectService projectService)
        {
            _projectService = projectService;
        }

        public async Task OnGet()
        {
            RequestedDate = DateTime.Today;

            await OnPostWithDate(RequestedDate);
        }

        public async Task OnPostWithDate(DateTime requestedDate)
        {
            var djelantikId = Convert.ToInt32(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var (evidencija, napomena) = await _projectService.GetProjectTimes(djelantikId, requestedDate);

            Evidencija = new TimesDTO
            {
                DjelatnikId = djelantikId,
                Evidencija = evidencija,
                Datum = requestedDate,
                Napomena = napomena
            };
        }

        public async Task OnPost(TimesDTO evidencija)
        {
            if (evidencija?.Evidencija == null || evidencija.Evidencija.Count == 0)
            {
                return;
            }

            RequestedDate = evidencija.Datum;
            Evidencija = evidencija;

            var djelantikId = Convert.ToInt32(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);

            await _projectService.SaveProjectTimes(evidencija.Evidencija, djelantikId, RequestedDate, evidencija.Napomena);
        }
    }
}

source/WTT/WTT.Web.ManagementPortal/Pages/TimeTrackingPage.cshtml
@page
@model WTT.Web.ManagementPortal.Pages.TimeTrackingPageModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Evidencija vremena";
    Layout = "_Layout";
    var disabledSubmit = true;

    for (var i = 0; i < Model.Evidencija.Evidencija.Count; i++)
    {
        disabledSubmit = disabledSubmit && Model.Evidencija.Evidencija[@i].Granted;
    }
}

<h1>Evidencija vremena</h1>

<div class="container">
    <form class="row" method="post">
        <input class="col-4 form-control" asp-for="@Model.RequestedDate" id="current-date-input">
        <div class="col-1"></div>
        <button type="submit" class="col-2 btn btn-dark" asp-page-handler="WithDate">Odi na datum</button>
    </form>

    <div style="margin-top:20px;"></div>

    <div class="row">
        <p class="col-3 font-weight-bold">Projekt</p>
        <p class="col-1 font-weight-bold">Zabilježeno</p>
        <p class="col-1 font-weight-bold">Start</p>
        <p class="col-1 font-weight-bold">Stop</p>
        <p class="col-2 font-weight-bold">Radni sati (min)</p>
        <p class="col-2 font-weight-bold">Prekovremeni sati (min)</p>
    </div>

    <form method="post">

        @for (var i = 0; i < Model.Evidencija.Evidencija.Count; i++)
        {
            <div class="row">
                <input type="hidden" name="Evidencija.Datum" value="@Model.Evidencija.Datum" />
                <input type="hidden" name="Evidencija.DjelatnikId" value="@Model.Evidencija.DjelatnikId" />
                <input type="hidden" name="Evidencija.Evidencija[@i].Id" value="@Model.Evidencija.Evidencija[i].Id" />
                <input type="hidden" name="Evidencija.Evidencija[@i].Name" value="@Model.Evidencija.Evidencija[i].Name" />
                <input type="hidden" name="Evidencija.Evidencija[@i].Granted" value="@Model.Evidencija.Evidencija[i].Granted.ToString()" />

                <p class="col-3">@Model.Evidencija.Evidencija[i].Name</p>

                <p class="col-1" id="timer_@Model.Evidencija.Evidencija[i].Id">@(Model.Evidencija.Evidencija[i].WorkMinutes + Model.Evidencija.Evidencija[i].OverTimeMinutes)</p>


                <div class=" col-1" style="display:flex; justify-content:center; align-items:center;">
                    <i class="fas fa-play" style="color:green;" id="@Model.Evidencija.Evidencija[i].Id"></i>
                </div>

                <div class="col-1" style="display:flex; justify-content:center; align-items:center;">
                    <i class="fas fa-stop hidden" style="color:red;"></i>
                </div>

                <input type="number" class="form-control col-2" id="timeInput_@Model.Evidencija.Evidencija[i].Id"
                       name="Evidencija.Evidencija[@i].WorkMinutes" value="@Model.Evidencija.Evidencija[i].WorkMinutes"
                       readonly="@Model.Evidencija.Evidencija[i].Granted" />
                <input type="number" class="form-control col-2" id="overtimeInput_@Model.Evidencija.Evidencija[i].Id"
                       name="Evidencija.Evidencija[@i].OverTimeMinutes" value="@Model.Evidencija.Evidencija[i].OverTimeMinutes"
                       readonly="@(Model.Evidencija.Evidencija[i].Granted || User.IsInRole("Student"))" />

            </div>
        }

        <div class="row">
            <button type="submit" class="btn btn-success" asp-page-handler="" disabled="@disabledSubmit">
                Predaj
            </button>
        </div>

        <div style="height:2px; background-color:black; margin-top:10px;"></div>
        <div class="row">
            <p class="col-3 font-weight-bold">Ukupno</p>
            <p class="col-1 font-weight-bold">@Model.Evidencija.Evidencija.Sum(x => x.WorkMinutes + x.OverTimeMinutes)</p>
            <p class="col-1 font-weight-bold"></p>
            <p class="col-1 font-weight-bold"></p>
            <p class="col-2 font-weight-bold">@Model.Evidencija.Evidencija.Sum(x => x.WorkMinutes)</p>
            <p class="col-2 font-weight-bold">@Model.Evidencija.Evidencija.Sum(x => x.OverTimeMinutes)</p>
        </div>

        <div style="height:2px; background-color:black;"></div>
        <div class="row" style="margin-top:10px;">
            <div class="form-group col-10">
                <label class="font-weight-bold" for="napomenaText">Napomena</label>
                <textarea class="form-control" rows="3" id="napomenaText" asp-for="@Model.Evidencija.Napomena">@Model.Evidencija.Napomena</textarea>
            </div>
        </div>
    </form>
</div>


<script>
    var projectId = 0;
    var time = 0;
    var startTime = Math.floor(Date.now() / 1000);
    var timer = false;
    var shouldntRunTimer = @disabledSubmit.ToString().ToLower();

    $(document).ready(function () {

        var startElements = document.getElementsByClassName("fas fa-play");
        for (var i = 0; i < startElements.length; i++) {
            (function () {
                var order = i;
                startElements[i].addEventListener('click', function () { startHandler(order) });
            }());
        }

        var endElements = document.getElementsByClassName("fas fa-stop");
        for (var i = 0; i < endElements.length; i++) {
            (function () {
                var order = i;
                endElements[i].addEventListener('click', function () { stopHandler(order) });
            } ());
        }
    });



    function startHandler(orderId) {
        if (shouldntRunTimer)
            return;

        var startElements = document.getElementsByClassName("fas fa-play");
        var endElements = document.getElementsByClassName("fas fa-stop");
        for (var i = 0; i < startElements.length; i++) {

            if (projectId > 0 && timer) {
                var name = "timeInput_" + projectId;
                var timeInputElement = document.getElementById(name);

                var myTime = parseInt(time);
                var currentTime = parseInt(timeInputElement.value);
                timeInputElement.value = currentTime + myTime;

                time = 0;
            }

            startElements[i].classList.remove("hidden");
            endElements[i].classList.add("hidden");

            if (i === orderId) {
                startElements[i].classList.add("hidden");
                endElements[i].classList.remove("hidden");

                projectId = startElements[i].id;

                startTime = Math.floor(Date.now() / 1000); //Get the starting time (right now) in seconds

                timer = true;
                startTimeCounter();
            }
        }
    }

    function stopHandler(orderId) {
        var startElements = document.getElementsByClassName("fas fa-play");
        var endElements = document.getElementsByClassName("fas fa-stop");
        for (var i = 0; i < endElements.length; i++) {

            startElements[i].classList.remove("hidden");
            endElements[i].classList.add("hidden");

            if (i === orderId) {
                var name = "timeInput_" + projectId;
                var timeInputElement = document.getElementById(name);

                var myTime = parseInt(time);
                var currentTime = parseInt(timeInputElement.value);
                timeInputElement.value = currentTime + myTime;

                time = 0;
                stopTimeCounter();
            }
        }
    }

    function startTimeCounter() {
        var now = Math.floor(Date.now() / 1000); // get the time now
        var diff = now - startTime; // diff in seconds between now and start
        var m = Math.floor(diff / 60); // get minutes value (quotient of diff)
        var s = Math.floor(diff % 60); // get seconds value (remainder of diff)

        time = m;

        m = checkTime(m); // add a leading zero if it's single digit
        s = checkTime(s); // add a leading zero if it's single digit

        if (timer) {
            var name = "timer_" + projectId;
            document.getElementById(name).innerHTML = m + ":" + s; // update the element where the timer will appear
        }

        var t = setTimeout(startTimeCounter, 500); // set a timeout to update the timer
    }

    function stopTimeCounter() {
        timer = false;
    }

    function checkTime(i) {
        if (i < 10) { i = "0" + i };  // add zero in front of numbers < 10
        return i;
    }
</script>

source/WTT/WTT.Web.ManagementPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width" />

    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/solid.min.css" />
    <link rel="stylesheet" href="~/css/customStyle.css" />

    <title>@ViewBag.Title</title>
</head>
<body>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>

    @if (User.Identity.IsAuthenticated)
    {
        <nav class="navbar navbar-dark bg-dark">
            <div class="container-fluid">

                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-page="/TimeTrackingPage">Evidencija vremena</a>
                        </li>

                        @if (User.IsInRole("Direktor") || User.IsInRole("Voditelj tima"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="TimeManagement" asp-action="OdobriVrijeme">Odobri vrijeme</a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>

        </nav>
        
    }

    <div style="height:30px;">

    </div>

    <div>
        @RenderBody()
    </div>
</body>
</html>

source/WTT/WTT.Web.ManagementPortal/Views/TimeManagement/Odobravanje.cshtml
@model TimesDTO
@{
    ViewBag.Title = "Odobri vrijeme";
}

    <div class="container">

        <h1>@Model.DjelatnikIme</h1>
        <p>@Model.DjelatnikTim</p>
        <p>@Model.Datum.ToString("dd.MM.yyyy")</p>

        <div style="margin-top:20px;"></div>

        @using (Html.BeginForm())
        {
            <div class="row">
                <p class="col-3 font-weight-bold">Projekt</p>
                <p class="col-2 font-weight-bold">Ukupno</p>
                <p class="col-2 font-weight-bold">Radni sati</p>
                <p class="col-2 font-weight-bold">Prekovremeni sati</p>
                <p class="col-2 font-weight-bold">Odobreno</p>
            </div>

            @for (var i = 0; i < Model.Evidencija.Count; i++)
            {
                <div class="row">
                    <input type="hidden" name="DjelatnikId" value="@Model.DjelatnikId" />
                    <input type="hidden" name="Datum" value="@Model.Datum" />
                    <input type="hidden" name="Evidencija[@i].Id" value="@Model.Evidencija[i].Id" />

                    <p class="col-3">@Model.Evidencija[i].Name</p>
                    <p class="col-2">@(Model.Evidencija[i].WorkMinutes + Model.Evidencija[i].OverTimeMinutes)</p>

                    <input type="number" class="form-control col-2" asp-for="@Model.Evidencija[i].WorkMinutes" value="@Model.Evidencija[i].WorkMinutes" readonly />
                    <input type="number" class="form-control col-2" asp-for="@Model.Evidencija[i].OverTimeMinutes" value="@Model.Evidencija[i].OverTimeMinutes" readonly />

                    <div class="form-check col-1 justify-content-center" style="display:flex; max-width:16.3333%; flex:0 0 12.3333%; align-items:center;">
                        @Html.CheckBoxFor(m => m.Evidencija[i].Granted, new { @class = "form-check-input col-1" })
                    </div>

                </div>
            }

            <button type="submit" asp-action="Odobravanje" asp-controller="TimeManagement" class="btn btn-primary">Odobri vrijeme</button>

            <div style="height:2px; background-color:black; margin-top:10px;"></div>
            <div class="row">
                <p class="col-3 font-weight-bold">Ukupno</p>
                <p class="col-1 font-weight-bold">@Model.Evidencija.Sum(x => x.WorkMinutes + x.OverTimeMinutes)</p>
                <p class="col-1 font-weight-bold"></p>
                <p class="col-1 font-weight-bold"></p>
                <p class="col-2 font-weight-bold">@Model.Evidencija.Sum(x => x.WorkMinutes)</p>
                <p class="col-2 font-weight-bold">@Model.Evidencija.Sum(x => x.OverTimeMinutes)</p>
            </div>

            <div style="height:2px; background-color:black;"></div>
            <div class="row" style="margin-top:10px;">
                <div class="form-group col-10">
                    <label class="font-weight-bold" for="napomenaText">Napomena</label>
                    <textarea class="form-control" rows="3" id="napomenaText" asp-for="@Model.Napomena">@Model.Napomena</textarea>
                </div>
            </div>
        }

    </div>

source/WTT/WTT.Web.ManagementPortal/Views/TimeManagement/OdobriVrijeme.cshtml
@model OdobriVrijemeDTO
@{
    ViewBag.Title = "Odobri vrijeme";
}

    <div class="container">
        <form method="post">
            <div class="form-group">
                <label asp-for="Datum">Datum</label>
                <input asp-for="@Model.Datum" class="form-control" type="date">
            </div>

            <div class="form-group">
                <label asp-for="DjelatnikId">Djelatnik</label>
                @Html.DropDownListFor(model => model.DjelatnikId, ViewBag.SelectListDjelatnika as List<SelectListItem>, new { @class = "form-control" })
            </div>
            
            <button type="submit" class="btn btn-primary">Odaberi radnika</button>
        </form>
    </div>